#ifndef TEXTS_EN_H
#define TEXTS_EN_H

//
//
// This file is auto-generated by 'create_translations_yaml_jinja2.py' script.
//
//


//      "pragma_label":  Txt
//      "array_label":   TXT
//      "indexes_count": 78
//      "array_length":  1636

#pragma section( enTxt, 0 )
#pragma section( enTxtData, 0 )
#pragma region( bankEnTxtArray, 0x8000, 0x809c, , TRANSLATION_EN_BANK, { enTxt}, 0x5c00 )
#pragma region( bankEnTxtData, 0x809c, 0x8700, , TRANSLATION_EN_BANK, { enTxtData}, 0x5c9c )

//      "pragma_label":  TxtCrew
//      "array_label":   TXT_CREW
//      "indexes_count": 7
//      "array_length":  69

#pragma section( enTxtCrew, 0 )
#pragma section( enTxtCrewData, 0 )
#pragma region( bankEnTxtCrewArray, 0x8701, 0x870f, , TRANSLATION_EN_BANK, { enTxtCrew}, 0x6400 )
#pragma region( bankEnTxtCrewData, 0x870f, 0x8754, , TRANSLATION_EN_BANK, { enTxtCrewData}, 0x640e )

//      "pragma_label":  TxtFarmland
//      "array_label":   TXT_FARMLAND
//      "indexes_count": 32
//      "array_length":  434

#pragma section( enTxtFarmland, 0 )
#pragma section( enTxtFarmlandData, 0 )
#pragma region( bankEnTxtFarmlandArray, 0x8755, 0x8795, , TRANSLATION_EN_BANK, { enTxtFarmland}, 0x6400 )
#pragma region( bankEnTxtFarmlandData, 0x8795, 0x8947, , TRANSLATION_EN_BANK, { enTxtFarmlandData}, 0x6440 )

//      "pragma_label":  TxtKitchen
//      "array_label":   TXT_KITCHEN
//      "indexes_count": 9
//      "array_length":  198

#pragma section( enTxtKitchen, 0 )
#pragma section( enTxtKitchenData, 0 )
#pragma region( bankEnTxtKitchenArray, 0x8948, 0x895a, , TRANSLATION_EN_BANK, { enTxtKitchen}, 0x6400 )
#pragma region( bankEnTxtKitchenData, 0x895a, 0x8a20, , TRANSLATION_EN_BANK, { enTxtKitchenData}, 0x6412 )

//      "pragma_label":  TxtVillageMap
//      "array_label":   TXT_VILLAGE_MAP
//      "indexes_count": 22
//      "array_length":  550

#pragma section( enTxtVillageMap, 0 )
#pragma section( enTxtVillageMapData, 0 )
#pragma region( bankEnTxtVillageMapArray, 0x8a21, 0x8a4d, , TRANSLATION_EN_BANK, { enTxtVillageMap}, 0x6400 )
#pragma region( bankEnTxtVillageMapData, 0x8a4d, 0x8c73, , TRANSLATION_EN_BANK, { enTxtVillageMapData}, 0x642c )

//      "pragma_label":  TxtOptionsMenu
//      "array_label":   TXT_OPTIONS_MENU
//      "indexes_count": 6
//      "array_length":  132

#pragma section( enTxtOptionsMenu, 0 )
#pragma section( enTxtOptionsMenuData, 0 )
#pragma region( bankEnTxtOptionsMenuArray, 0x8c74, 0x8c80, , TRANSLATION_EN_BANK, { enTxtOptionsMenu}, 0x6400 )
#pragma region( bankEnTxtOptionsMenuData, 0x8c80, 0x8d04, , TRANSLATION_EN_BANK, { enTxtOptionsMenuData}, 0x640c )

//      "pragma_label":  TxtTaskManager
//      "array_label":   TXT_TASK_MANAGER
//      "indexes_count": 11
//      "array_length":  426

#pragma section( enTxtTaskManager, 0 )
#pragma section( enTxtTaskManagerData, 0 )
#pragma region( bankEnTxtTaskManagerArray, 0x8d05, 0x8d1b, , TRANSLATION_EN_BANK, { enTxtTaskManager}, 0x6400 )
#pragma region( bankEnTxtTaskManagerData, 0x8d1b, 0x8ec5, , TRANSLATION_EN_BANK, { enTxtTaskManagerData}, 0x6416 )




#pragma compile("textsEN.c")
#endif