#ifndef TEXTS_EN_H
#define TEXTS_EN_H

//
//
// This file is auto-generated by 'create_translations_yaml_jinja2.py' script.
//
//


//      "pragma_label":  Txt
//      "array_label":   TXT
//      "indexes_count": 84
//      "array_length":  1747

#pragma section( enTxt, 0 )
#pragma section( enTxtData, 0 )
#pragma region( bankEnTxtArray, 0x8000, 0x80a8, , TRANSLATION_EN_BANK, { enTxt}, 0x5c00 )
#pragma region( bankEnTxtData, 0x80a8, 0x877b, , TRANSLATION_EN_BANK, { enTxtData}, 0x5ca8 )

//      "pragma_label":  TxtCrew
//      "array_label":   TXT_CREW
//      "indexes_count": 7
//      "array_length":  62

#pragma section( enTxtCrew, 0 )
#pragma section( enTxtCrewData, 0 )
#pragma region( bankEnTxtCrewArray, 0x877c, 0x878a, , TRANSLATION_EN_BANK, { enTxtCrew}, 0x6400 )
#pragma region( bankEnTxtCrewData, 0x878a, 0x87c8, , TRANSLATION_EN_BANK, { enTxtCrewData}, 0x640e )

//      "pragma_label":  TxtFarmland
//      "array_label":   TXT_FARMLAND
//      "indexes_count": 32
//      "array_length":  434

#pragma section( enTxtFarmland, 0 )
#pragma section( enTxtFarmlandData, 0 )
#pragma region( bankEnTxtFarmlandArray, 0x87c9, 0x8809, , TRANSLATION_EN_BANK, { enTxtFarmland}, 0x6400 )
#pragma region( bankEnTxtFarmlandData, 0x8809, 0x89bb, , TRANSLATION_EN_BANK, { enTxtFarmlandData}, 0x6440 )

//      "pragma_label":  TxtKitchen
//      "array_label":   TXT_KITCHEN
//      "indexes_count": 9
//      "array_length":  198

#pragma section( enTxtKitchen, 0 )
#pragma section( enTxtKitchenData, 0 )
#pragma region( bankEnTxtKitchenArray, 0x89bc, 0x89ce, , TRANSLATION_EN_BANK, { enTxtKitchen}, 0x6400 )
#pragma region( bankEnTxtKitchenData, 0x89ce, 0x8a94, , TRANSLATION_EN_BANK, { enTxtKitchenData}, 0x6412 )

//      "pragma_label":  TxtVillageMap
//      "array_label":   TXT_VILLAGE_MAP
//      "indexes_count": 22
//      "array_length":  550

#pragma section( enTxtVillageMap, 0 )
#pragma section( enTxtVillageMapData, 0 )
#pragma region( bankEnTxtVillageMapArray, 0x8a95, 0x8ac1, , TRANSLATION_EN_BANK, { enTxtVillageMap}, 0x6400 )
#pragma region( bankEnTxtVillageMapData, 0x8ac1, 0x8ce7, , TRANSLATION_EN_BANK, { enTxtVillageMapData}, 0x642c )

//      "pragma_label":  TxtOptionsMenu
//      "array_label":   TXT_OPTIONS_MENU
//      "indexes_count": 7
//      "array_length":  162

#pragma section( enTxtOptionsMenu, 0 )
#pragma section( enTxtOptionsMenuData, 0 )
#pragma region( bankEnTxtOptionsMenuArray, 0x8ce8, 0x8cf6, , TRANSLATION_EN_BANK, { enTxtOptionsMenu}, 0x6400 )
#pragma region( bankEnTxtOptionsMenuData, 0x8cf6, 0x8d98, , TRANSLATION_EN_BANK, { enTxtOptionsMenuData}, 0x640e )

//      "pragma_label":  TxtTaskManager
//      "array_label":   TXT_TASK_MANAGER
//      "indexes_count": 11
//      "array_length":  426

#pragma section( enTxtTaskManager, 0 )
#pragma section( enTxtTaskManagerData, 0 )
#pragma region( bankEnTxtTaskManagerArray, 0x8d99, 0x8daf, , TRANSLATION_EN_BANK, { enTxtTaskManager}, 0x6400 )
#pragma region( bankEnTxtTaskManagerData, 0x8daf, 0x8f59, , TRANSLATION_EN_BANK, { enTxtTaskManagerData}, 0x6416 )




#pragma compile("textsEN.c")
#endif